gen_data['character'] = [
  'You are <i> {name}</i>.<br>You have {physique} physique, {skin} skin, {hair} hair, and {face} face.<br>You speak in a {speech} manner.<br>You are {vice} yet {virtue}.<p>In another life, you were a {class}'
]

gen_data['class'] = [
  '<b>warrior</b>.<h3>Equipment</h3><li><b>Key item: </b>Linden wood shield</li><li><b>Armour: </b>Chainmail (2 Defence, bulky)</li><li><b>Shield: </b>Linden wood shield (<b>key item</b>, +1 Defence)</li><li><b>Weapon(s): </b>Bearded axe (d8), ash wood spear (d6, 20\')</li><li><b>Magic: </b>None</li><li><b>Gear, tools & trinkets: </b>Memento of defeat</li><li><b>Inventory: </b> Remaining free slots, <b>4 out of 10</b></li><h3>Attributes</h3><table><tr align="left"><th>Defence: </th><td align="right" id="def">3</td></tr></table>',
  '<b>skald</b>.<h3>Equipment</h3><li><b>Key item: </b>Runic focus</li><li><b>Armour: </b>Reindeer hide (1 Defence) and leather hood (+1 Defence)</li><li><b>Shield: </b>None</li><li><b>Weapon(s): </b>Steel sword (d6)</li><li><b>Magic: </b>Sagas ({saga})</li><li><b>Gear, tools & trinkets: </b>Runic focus (key, small), sacred waters (d10), sacrificial bundle (small)</li><li><b>Inventory: </b>Remaining free slots, <b>5 out of 10</b></li><h3>Attributes</h3><table><tr align="left"><th>Defence: </th><td align="right" id="def">2</td></tr></table>',
  '<b>scout</b>.<h3>Equipment</h3><li><b>Key item: </b>Hunting knives</li><li><b>Armour: </b>Quilted cloth (1 Defence)</li><li><b>Shield: </b>None</li><li><b>Weapon(s): </b>Hunting knives (key, d6), elm shortbow (bulky, d6, 60\')</li><li><b>Magic: </b>None</li><li><b>Gear, tools & trinkets: </b>Fire oil (blast, d8), skeleton key (small)</li><li><b>Inventory: </b>Remaining free slots, <b>5 out of 10</b></li><h3>Attributes</h3><table><tr align="left"><th>Defence: </th><td align="right" id="def">1</td></tr></table>',
  '<b>seer</b>.<h3>Equipment</h3><li><b>Key item: </b>Yew staff</li><li><b>Armour: </b>Stout linen (0 Defence)</li><li><b>Shield: </b>None</li><li><b>Weapon(s): </b>Yew staff (key, d6)</li><li><b>Magic: </b>Spells ({runestone})</li><li><b>Gear, tools & trinkets: </b>Bleached jawbone</li><li><b>Inventory: </b>Remaining free slots, <b>7 out of 10</b></li><h3>Attributes</h3><table><tr align="left"><th>Defence: </th><td align="right" id="def">0</td></tr></table>'
]

gen_data['name'] = [
'Alvar'
, 'Anna'
, 'Anri'
, 'Ari'
, 'Arne'
, 'Arnkatla'
, 'Astrid'
, 'Auður'
, 'Birger'
, 'Bjørn'
, 'Bo'
, 'Bodil'
, 'Darri'
, 'Edda'
, 'Einar'
, 'Emil'
, 'Erik'
, 'Estrid'
, 'Flosi'
, 'Flóki'
, 'Freyja'
, 'Frida'
, 'Frode'
, 'Funi'
, 'Gertrud'
, 'Gorm'
, 'Gro'
, 'Gunhild'
, 'Gunnar'
, 'Guðmundur'
, 'Guðrún'
, 'Halfdan'
, 'Hallbera'
, 'Harald'
, 'Harpa'
, 'Hekla'
, 'Helgi'
, 'Hilda'
, 'Hilmir'
, 'Hrefna'
, 'Inga'
, 'Ingibjörg'
, 'Ingólfur'
, 'Jóhanna'
, 'Jón'
, 'Karitas'
, 'Katla'
, 'Kaðlín'
, 'Ketill'
, 'Knud'
, 'Kristján'
, 'Kristín'
, 'Kåre'
, 'Leif'
, 'Lind'
, 'Liv'
, 'Logi'
, 'Lukka'
, 'Magnús'
, 'Margrét'
, 'María'
, 'Njal'
, 'Nói'
, 'Orri'
, 'Randi'
, 'Revna'
, 'Roar'
, 'Rune'
, 'Saga'
, 'Salvar'
, 'Sif'
, 'Sigmar'
, 'Signe'
, 'Sigrid'
, 'Sigríður'
, 'Sigrún'
, 'Skarde'
, 'Stefán'
, 'Sten'
, 'Sune'
, 'Sunna'
, 'Svend'
, 'Thurid'
, 'Thyra'
, 'Toke'
, 'Tora'
, 'Torsten'
, 'Tove'
, 'Troels'
, 'Trygve'
, 'Ulfhild'
, 'Valgerður'
, 'Vilmar'
, 'Von'
, 'Yrsa'
, 'Åge'
, 'Åse'
, 'Ólafur'
, 'Ødger'
, 'Þuríður'
]

gen_data['physique'] = [
'an athletic'
, 'a brawny'
, 'a diminutive'
, 'a lanky'
, 'a rugged'
, 'a slim'
, 'a short'
, 'a statuesque'
, 'a stout'
, 'a towering'
]

gen_data['skin'] = [
'wrinkled'
, 'dark'
, 'elongated'
, 'pockmarked'
, 'rosy'
, 'rough'
, 'smooth'
, 'tanned'
, 'scarred'
, 'weathered'
]

gen_data['hair'] = [
'shaved'
, 'braided'
, 'curly'
, 'matted'
, 'frizzy'
, 'flowing'
, 'luxurious'
, 'oily'
, 'wavy'
, 'wispy'
]

gen_data['face'] = [
'a bony'
, 'a damaged'
, 'a chiselled'
, 'an elongated'
, 'a pale'
, 'a symmetrical'
, 'a fierce'
, 'a sharp'
, 'a square'
, 'a sunken'
]

gen_data['speech'] = [
'blunt'
, 'booming'
, 'cryptic'
, 'droning'
, 'formal'
, 'gravelly'
, 'precise'
, 'squeaky'
, 'eloquent'
, 'whispery'
]

gen_data['virtue'] = [
'ambitious'
, 'cautious'
, 'courageous'
, 'disciplined'
, 'gregarious'
, 'honourable'
, 'humble'
, 'merciful'
, 'serene'
, 'tolerant'
]

gen_data['vice'] = [
'aggressive'
, 'bitter'
, 'craven'
, 'deceitful'
, 'greedy'
, 'lazy'
, 'nervous'
, 'rude'
, 'vain'
, 'vengeful'
]

gen_data['misfortune'] = [
  'abandoned'
,  'addicted'
,  'blackmailed'
,  'condemned'
,  'cursed'
,  'abandoned'
,  'addicted'
,  'blackmailed'
,  'condemned'
,  'cursed'
]

gen_data['saga'] = [
  'lightning spear'
,  'cure wounds'
]

gen_data['runestone'] = [
  'slow'
,  'seiðr spear'
]