gen_data['character'] = [
  'You are <i> {name}</i>.<br>You have {physique} physique, {skin} skin, {hair} hair, and {face} face.<br>You speak in a {speech} manner.<br>You are {vice} yet {virtue}.<br>In another life, you were a {class}'
]

gen_data['class'] = [
  '<h3>Warrior</h3><p>In another life you might have been a soldier, a guardsman, a shieldmaiden, or a raider. Your shield was always strapped to your arm and your axe and spear always to hand.<p>You sang the songs of battle and drank to victory and defeat in smoke-filled halls.<p>In combat, you favoured the direct approach, relying on your sturdy armour to deflect any blows while giving you time to land your own.<p>In the time before you prayed to Oðinn for a glorious death but now your fate is your own to choose.<h3>Equipment</h3><li><b>Armour: </b>Chainmail (2 Defence, bulky).</li><li><b>Shield: </b>Linden wood shield (<b>key item</b>, +1 Defence).</li><li><b>Weapon(s): </b>Bearded axe (d8), ash wood spear (d6, 20\')</li><li><b>Gear, tools & trinkets: </b>Memento of defeat.</li><li><b>Inventory: 4</b> free slots remaining out of <b>10</b>.</li>',
  '<h3>Skald</h3>You have {physique} physique, {skin} skin, {hair} hair, and {face} face.<br>You speak in a {speech} manner.<br>You are {vice} yet {virtue}.',
  '<h3>Scout</h3>You have {physique} physique, {skin} skin, {hair} hair, and {face} face.<br>You speak in a {speech} manner.<br>You are {vice} yet {virtue}.',
  '<h3>Seer</h3>You have {physique} physique, {skin} skin, {hair} hair, and {face} face.<br>You speak in a {speech} manner.<br>You are {vice} yet {virtue}.'
]

gen_data['name'] = [
'Alvar'
, 'Anna'
, 'Anri'
, 'Ari'
, 'Arne'
, 'Arnkatla'
, 'Astrid'
, 'Auður'
, 'Birger'
, 'Bjørn'
, 'Bo'
, 'Bodil'
, 'Darri'
, 'Edda'
, 'Einar'
, 'Emil'
, 'Erik'
, 'Estrid'
, 'Flosi'
, 'Flóki'
, 'Freyja'
, 'Frida'
, 'Frode'
, 'Funi'
, 'Gertrud'
, 'Gorm'
, 'Gro'
, 'Gunhild'
, 'Gunnar'
, 'Guðmundur'
, 'Guðrún'
, 'Halfdan'
, 'Hallbera'
, 'Harald'
, 'Harpa'
, 'Hekla'
, 'Helgi'
, 'Hilda'
, 'Hilmir'
, 'Hrefna'
, 'Inga'
, 'Ingibjörg'
, 'Ingólfur'
, 'Jóhanna'
, 'Jón'
, 'Karitas'
, 'Katla'
, 'Kaðlín'
, 'Ketill'
, 'Knud'
, 'Kristján'
, 'Kristín'
, 'Kåre'
, 'Leif'
, 'Lind'
, 'Liv'
, 'Logi'
, 'Lukka'
, 'Magnús'
, 'Margrét'
, 'María'
, 'Njal'
, 'Nói'
, 'Orri'
, 'Randi'
, 'Revna'
, 'Roar'
, 'Rune'
, 'Saga'
, 'Salvar'
, 'Sif'
, 'Sigmar'
, 'Signe'
, 'Sigrid'
, 'Sigríður'
, 'Sigrún'
, 'Skarde'
, 'Stefán'
, 'Sten'
, 'Sune'
, 'Sunna'
, 'Svend'
, 'Thurid'
, 'Thyra'
, 'Toke'
, 'Tora'
, 'Torsten'
, 'Tove'
, 'Troels'
, 'Trygve'
, 'Ulfhild'
, 'Valgerður'
, 'Vilmar'
, 'Von'
, 'Yrsa'
, 'Åge'
, 'Åse'
, 'Ólafur'
, 'Ødger'
, 'Þuríður'
]

gen_data['physique'] = [
'an athletic'
, 'a brawny'
, 'a diminutive'
, 'a lanky'
, 'a rugged'
, 'a slim'
, 'a short'
, 'a statuesque'
, 'a stout'
, 'a towering'
]

gen_data['skin'] = [
'wrinkled'
, 'dark'
, 'elongated'
, 'pockmarked'
, 'rosy'
, 'rough'
, 'smooth'
, 'tanned'
, 'scarred'
, 'weathered'
]

gen_data['hair'] = [
'shaved'
, 'braided'
, 'curly'
, 'matted'
, 'frizzy'
, 'flowing'
, 'luxurious'
, 'oily'
, 'wavy'
, 'wispy'
]

gen_data['face'] = [
'a bony'
, 'a damaged'
, 'a chiselled'
, 'an elongated'
, 'a pale'
, 'a symmetrical'
, 'a fierce'
, 'a sharp'
, 'a square'
, 'a sunken'
]

gen_data['speech'] = [
'blunt'
, 'booming'
, 'cryptic'
, 'droning'
, 'formal'
, 'gravelly'
, 'precise'
, 'squeaky'
, 'eloquent'
, 'whispery'
]

gen_data['virtue'] = [
'ambitious'
, 'cautious'
, 'courageous'
, 'disciplined'
, 'gregarious'
, 'honourable'
, 'humble'
, 'merciful'
, 'serene'
, 'tolerant'
]

gen_data['vice'] = [
'aggressive'
, 'bitter'
, 'craven'
, 'deceitful'
, 'greedy'
, 'lazy'
, 'nervous'
, 'rude'
, 'vain'
, 'vengeful'
]

gen_data['misfortune'] = [
  'abandoned'
,  'addicted'
,  'blackmailed'
,  'condemned'
,  'cursed'
,  'abandoned'
,  'addicted'
,  'blackmailed'
,  'condemned'
,  'cursed'
]