# Setup
title:               Runecairn
tagline:             'Norse fantasy tabletop roleplaying game'
description:         '<a href="https://runecairn.byodinsbeardrpg.com"><img src="https://runecairn.byodinsbeardrpg.com/public/runecairn_logo_colour.png"></a>'
url:                 https://runecairn.byodinsbeardrpg.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Colin Le Sueur
  url:               https://twitter.com/byodinsbeardrpg
  email:             colin@byodinsbeardrpg.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
