# Setup
title:               By Odin's Beard RPG
tagline:             'Tabletop roleplaying games'
description:         '<img src="https://github.com/byodinsbeardrpg/byodinsbeardrpg.github.io/blob/bb4368b1b3b9c45e9fc50f8d16c0dbf35d238177/public/by_odins_beard_logo_and_text_600px_white.png">'
url:                 https://byodinsbeardrpg.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Colin Le Sueur
  url:               https://twitter.com/byodinsbeardrpg
  email:             colin@byodinsbeardrpg.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
