# Setup
title:               By Odin's Beard RPG
tagline:             'Tabletop roleplaying games'
description:         '<img src="https://byodinsbeardrpg.github.io/public/by_odins_beard_logo_and_text_600px_white.png"
url:                 https://byodinsbeardrpg.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Colin Le Sueur
  url:               https://twitter.com/byodinsbeardrpg
  email:             colin@byodinsbeardrpg.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
